### ISSUE TITLE
Bug: "error":"invalid_state"

### ISSUE THREAD

**Issue by iamjuney** [kinde-starter-kits/sveltekit-starter-kit#8]
### Prerequisites

- [X] I have searched the repository’s issues and [Kinde community](https://thekindecommunity.slack.com/archives/C04K316BXEH) to ensure my issue isn’t a duplicate
- [X] I have read the [contributing guidelines](https://github.com/kinde-starter-kits/.github/blob/ff8d5c462e56772810bca53f750fd3610a00d673/.github/CONTRIBUTING.md)
- [X] I agree to the terms within the [code of conduct](https://github.com/kinde-starter-kits/.github/blob/ff8d5c462e56772810bca53f750fd3610a00d673/.github/CODE_OF_CONDUCT.md)

### Describe the issue

whenever i sign up or sign in i got the error.

{"error":"invalid_state","error_description":"The state is missing or does not have enough characters and is therefore considered too weak. Request parameter 'state' must be at least be 8 characters long to ensure sufficient entropy."}

i followed the steps and stuff but cant get it working. sorry noobie here.

### Starter kit URL

https://github.com/kinde-starter-kits/sveltekit-starter-kit/

### Operating system(s)

Other Linux

### Operating system version(s)

Pop!_OS 22.04 LTS x86_64 

### Further environment details

Chrome v119
Node.js v20.2.0

**Comment by coel** [comment]
Sorry about this @iamjuney , there was a bug which has now been fixed.  If you pull the latest code or update to the latest Svelte SDK it should be fixed.  Let us know if you still experience any issues.

**Comment by iamjuney** [comment]
@coel I'm still getting the same error 😔.

**Comment by coel** [comment]
@iamjuney, can you see if you have an empty `ac-state-key` cookie?

**Comment by iamjuney** [comment]
@coel hey it works. thank you
